spring.application.name=imdb-clone

spring.datasource.url=jdbc:postgresql://localhost:5430/imdbclone
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.security.user.password=admin
springdoc.enable-spring-security=false

spring.jpa.hibernate.ddl-auto=update

jwt.secret=VFJsEYyV8b5Xlb6ptpRIU01YvKKFw6sHF4FDaYwmvfA=
jwt.expiration=36000000